[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0.86"
chrono = "^0.4.38"
clap = { version = "^4.5.4", features = ["derive"] }
config = "^0.14.0"
google-calendar = "^0.7.0"
pandoc = "^0.8.11"
reqwest = { version = "^0.12.4", features = ["json"] }
serde = { version = "^1.0.202", features = ["derive"] }
serde_json = { version = "^1.0.117", features = ["std"] }
tempfile = "^3.10.1"
tokio = { version = "^1.37.0", features = ["rt", "rt-multi-thread"] }
v_utils = { version = "^1.3.6", features = ["io"] }
derive-new = "^0.6.0"
