[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
chrono = "0.4.31"
clap = { version = "4.4.13", features = ["derive"] }
dirs = "5.0.1"
pandoc = "0.8.11"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = { version = "1.0.107", features = ["std"] }
tempfile = "3.9.0"
toml = "0.8.8"
